### ISSUE TITLE
Test with basic-auth on

### ISSUE THREAD

**Issue by alexellis** [openfaas/certifier#44]
The production use-case is to use auth, so can we move to using auth?

From the README:

> The tests assume a local environment with basic authentication turned off.

**Comment by LucasRoesler** [comment]
I was looking into this, but I think it makes the most sense after #45. Switching to the proxy SDK from the CLI means we can reuse the proven auth implementation. Perhaps we can even reuse the client initialization from the config so that the certifier usage will be

```sh
faas-cli login .... // or faas-cli auth 
make test
```

This would immediate allow us to test any deployment that faas-cli will support.
